# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TeslaSpotting' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TeslaSpotting
  pod 'react-native-camera', path: '../node_modules/react-native-camera'

  target 'TeslaSpotting-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TeslaSpottingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'TeslaSpotting-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TeslaSpotting-tvOS

  target 'TeslaSpotting-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
